site_name: Datoviz Documentation
repo_url: https://github.com/datoviz/datoviz
site_description: High-performance interactive scientific data visualization library
site_author: Cyrille Rossant
theme:
  name: material
  logo: images/logow.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "utils.hooks:config_hook"
        on_page_markdown: "utils.hooks:page_hook"
nav:
  - Home: 'index.md'
  - User manual:
      - Introduction: 'user/index.md'
      - Installation: 'user/install.md'
      - Quickstart: 'user/quickstart.md'
      - Colormaps: 'user/colormaps.md'
      - Visuals: 'user/visuals.md'
      - Scene: 'user/scene.md'
      - Callbacks: 'user/callbacks.md'
      - GUI: 'user/gui.md'
  - Expert manual:
      - Introduction: 'expert/index.md'
      - Vulkan crash course: 'expert/vulkan.md'
      - Canvas: 'expert/canvas.md'
      - Custom visuals: 'expert/visual.md'
      - Graphics library: 'expert/graphics.md'
      - Custom graphics: 'expert/glsl.md'
      - Library architecture: 'expert/architecture.md'
      - Mesh and triangulations: 'expert/mesh.md'
      - Developer notes: 'expert/developer.md'
      - Standalone C examples: 'expert/standalone.md'
  - C API reference:
      - Index: 'api/index.md'
      - Scene API: 'api/scene.md'
      - Visual API: 'api/visual.md'
      - Controller API: 'api/controller.md'
      - Canvas API: 'api/canvas.md'
      - GPU API: 'api/gpu.md'
      - vklite API: 'api/vklite.md'
      - Misc API: 'api/misc.md'
      - Enumerations: 'api/enums.md'
  - Gallery:
      - Introduction: 'gallery.md'
