site_name: Visky Documentation
repo_url: https://github.com/viskydev/visky
site_description: High-performance interactive scientific data visualization library
site_author: Cyrille Rossant
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
markdown_extensions:
  - toc:
      permalink: true
  - abbr
  - admonition
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
plugins:
  - search
nav:
  - Home: 'index.md'
  - Quick start: 'quickstart/index.md'
  - User manual: 'user/index.md'
  - Expert manual: 'expert/index.md'
  - Developer manual: 'developer/index.md'
  - Gallery: 'gallery.md'
  - API: 'api.md'
  - Quick start:
      - Introduction: 'quickstart/index.md'
      - Install instructions: 'quickstart/install.md'
      - Hello triangle: 'quickstart/hello.md'
      - Basic interface: 'quickstart/basic.md'
  - User manual:
      - Introduction: 'user/index.md'
      - Abstractions: 'user/abstractions.md'
      - The canvas: 'user/canvas.md'
      - The scene: 'user/scene.md'
      - Colormaps: 'user/color.md'
      - Visuals: 'user/visuals.md'
      - 2D plotting: 'user/visuals2D.md'
      - 3D plotting: 'user/visuals3D.md'
      - Meshes and triangulations: 'user/mesh.md'
      - Coordinate systems and transformations: 'user/transform.md'
      - Interactivity: 'user/interact.md'
      - Integrated GUI: 'user/gui.md'
      - Backends: 'user/backends.md'
  - Expert manual:
      - Introduction: 'expert/index.md'
      - 'vklite: Vulkan for Humans': 'expert/vklite.md'
      - 'Custom visuals: beginner': 'expert/custom1.md'
      - 'Custom visuals: intermediate': 'expert/custom2.md'
      - 'Custom visuals: advanced': 'expert/custom3.md'
  - Developer manual:
      - Introduction: 'developer/index.md'
      - Coding practices: 'developer/coding.md'
      - Code organization: 'developer/code.md'
      - Build scripts and tools: 'developer/build.md'
      - Testing: 'developer/test.md'
      - Continuous integration: 'developer/ci.md'
      - Implementation details: 'developer/implementation.md'

  - Gallery:
      - Introduction: 'gallery.md'
  - API:
      - API: 'api.md'
