site_name: Visky Documentation
repo_url: https://github.com/viskydev/visky
site_description: High-performance interactive scientific data visualization library
site_author: Cyrille Rossant
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - admonition
  - attr_list
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_config: "utils.hooks:config_hook"
        on_page_markdown: "utils.hooks:page_hook"
nav:
  - Home: 'index.md'
  - Quick start:
      - Introduction: 'quickstart/index.md'
      - Install instructions: 'quickstart/install.md'
      - Basic interface: 'quickstart/basic.md'
  - User manual:
      - Introduction: 'user/index.md'
      - Abstractions: 'user/abstractions.md'
      - The canvas: 'user/canvas.md'
      - The scene: 'user/scene.md'
      - Colormaps: 'user/color.md'
      - Visuals: 'user/visuals.md'
      - 2D plotting: 'user/visuals2D.md'
      - 3D plotting: 'user/visuals3D.md'
      - Graphics: 'user/graphics.md'
      - Meshes and triangulations: 'user/mesh.md'
      - Coordinate systems and transformations: 'user/transform.md'
      - Interactivity: 'user/interact.md'
      - Integrated GUI: 'user/gui.md'
      - Backends: 'user/backends.md'
  - Expert manual:
      - Introduction: 'expert/index.md'
      - 'vklite: Vulkan for Humans': 'expert/vklite.md'
      - 'Custom visuals: beginner': 'expert/custom1.md'
      - 'Custom visuals: intermediate': 'expert/custom2.md'
      - 'Custom visuals: advanced': 'expert/custom3.md'
  - Developer manual:
      - Introduction: 'developer/index.md'
      - Coding practices: 'developer/coding.md'
      - Code organization: 'developer/code.md'
      - Build scripts and tools: 'developer/build.md'
      - Testing: 'developer/test.md'
      - Continuous integration: 'developer/ci.md'
      - Implementation details: 'developer/implementation.md'
  - C API reference:
      - Index: 'api/index.md'
      - Scene API: 'api/scene.md'
      - Visual API: 'api/visual.md'
      - Controller API: 'api/controller.md'
      - Canvas API: 'api/canvas.md'
      - GPU API: 'api/gpu.md'
      - vklite API: 'api/vklite.md'
      - Misc API: 'api/misc.md'
      - Enumerations: 'api/enums.md'
  - Gallery:
      - Introduction: 'gallery.md'
